#!/bin/sh
### BEGIN INIT INFO
# Provides:          sshd
# Default-Start:     
# Default-Stop:      
# Short-Description: Starts or stops the sshd daemon.
### END INIT INFO

NAME=sshd
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
SYSCONF_DIR=/etc/ssh

if ! test -x "$DAEMON" ;then 
	echo $DAEMON": Not found or no execution permission"
	exit 0
fi

gen_ssh_hostkeys () {

	if [ ! -e ${SYSCONF_DIR}/ssh_host_key -o 				\
		! -e ${SYSCONF_DIR}/ssh_host_dsa_key -o				\
		! -e ${SYSCONF_DIR}/ssh_host_rsa_key -o				\
		! -e ${SYSCONF_DIR}/ssh_host_ecdsa_key -o			\
		! -e ${SYSCONF_DIR}/ssh_host_ed25519_key ];	then
		rm -rf ${SYSCONF_DIR}/ssh_host*
		echo "Generating Keys ..."
		ssh-keygen -q -t rsa1 -f ${SYSCONF_DIR}/ssh_host_key -N ""          &&
		ssh-keygen -q -t dsa -f ${SYSCONF_DIR}/ssh_host_dsa_key -N ""       &&
		ssh-keygen -q -t rsa -f ${SYSCONF_DIR}/ssh_host_rsa_key -N ""       &&
		ssh-keygen -q -t ecdsa -f ${SYSCONF_DIR}/ssh_host_ecdsa_key -N ""   &&
		ssh-keygen -q -t ed25519 -f ${SYSCONF_DIR}/ssh_host_ed25519_key -N "" ;
	fi

}

gen_ssh_id_rsa () {

	if [ ! -d /root -o ! -d /root/.ssh -o ! -e /root/.ssh/id_rsa ];	then
		echo "Generating id_rsa ..."
		mkdir -p /root/.ssh
		(echo -e "\n\n") | ssh-keygen
		rm -rf /etc/ssh_host_*
		gen_ssh_hostkeys
	
	fi

}

group_passwd () {

	touch /etc/group /etc/passwd

	if ! grep -q root "/etc/group"; then
		echo "Creating /etc/group and adding entries ... "
		addgroup -S root
	fi

	if ! grep -q root "/etc/passwd"; then
		echo "Creating /etc/passwd and adding entries ... "
		adduser root -G root -u 0 -D -h /root
		#echo "Enter Passwd for root: "
		echo "Pre-chosen Passwd for root: letmein "
		(echo letmein) | passwd
	fi

	if ! grep -q sshd "/etc/passwd"; then
		echo "Adding sshd user to passwd ..."
		mkdir -p /var/run
		adduser sshd -G root -D -h /var/run/sshd -s /usr/sbin/nologin
		#sshd:x:117:65534::/var/run/sshd:/usr/sbin/nologin
	fi
}

_start () {

	if ! test -d /dev/pts	;then :
		# These below 2 steps are necessary for ssh connection to HOST
		echo "Mounting devpts to /dev/pts"
		mkdir -p /dev/pts
		mount -t devpts devpts  /dev/pts
	fi

	group_passwd
	gen_ssh_id_rsa
	gen_ssh_hostkeys

}


case "$1" in
    start)
	rm -rf $PIDFILE
	if [ ! -e $PIDFILE ]; then
	        echo "Starting daemon" "$NAME"
		_start
		start-stop-daemon --start --quiet --oknodo -m --pidfile "$PIDFILE" --exec "$DAEMON"
		#echo $?
	else
		echo "$NAME-daemon is running."
	fi
        ;;
    stop)
	if [ -e $PIDFILE ]; then
	        echo "Stopping daemon" "$NAME"
		start-stop-daemon --stop --quiet --oknodo --pidfile "$PIDFILE"
		rm -rf $PIDFILE
	        #echo $?
	else
		echo "$NAME-daemon is not running."
	fi
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    status)
        if [ -e $PIDFILE ] ; then
		echo "SSH is upon running"
	else
		echo "SSH is not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0
