// v:11.0.7
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var noskimwords = true;
var noskoupon = true;
var noskimproducts = true;
var skimwords_instant = true;
var skimlinks_domain = 'wordpress.redirectingat.com';
var skimlink_legacy_support = true;
(function(){var Hb,Ib,K,Jb,Kb,Lb,Mb,Nb,M,db,Ob,Pb,eb,Qb,n,q,Rb,Sb,Tb,fb,ea,Ub,Vb,gb,Wb,D,Xb,sa,Yb,k,ta,Ja,hb,Zb,$b,ac,bc,ib,m,E,ua,F,fa,U,va,V,Ka,ga,j,W,ha,ia,p,ja,cc,G,ka,jb,La,X,R,kb,wa,Y,dc,ec,Ma,fc,Na,Z,gc,hc,$,lb,ic,jc,kc,lc,mc,nc,x,oc,pc,la,Oa,qc,Pa,xa,ma,mb,rc,nb,ob,pb,sc,qb,rb,tc,sb,uc,Qa,vc,o,tb,wc,xc,yc,zc,ya,Ac,Bc,Cc,Dc,ub,Ec,za,na,vb,Fc,Gc,Hc,Ic,wb,Jc,Ra,B,Kc,Lc,Mc,xb,H,Nc,Aa,Sa,Ta,yb,aa,Ua,Ba,Ca,Oc,S,T,oa,Va,zb,Da,P,Wa,Xa,N,pa,y,C,ba,Pc,Qc,ca,Ya,da,Ab,Rc,Ea,Sc,I,Za,$a,Tc,ab,A,Bb,qa,bb,
Cb,z,r,Db,ra,Fa,L,Ga,cb,Ha,Ia,J,Eb,u,O,Fb,g,w={}.hasOwnProperty,Gb=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};V=Ka=null;ga=/http:/g;m=function(){return function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}}(this)();
X=[];Y=[];G={};jb=(new Date).getTime();ka=[];cc=["buy.itunes.apple.com","itunes.apple.com","itunes.com"];La=[];W=F=U=null;va=!1;ha=[];fa=[];ia=[];E=null;ua={};pa=N=Wa=Ca=Ba=P=C=null;aa=[];T=[];S=Xa=Ta=Ua=Da=null;oa=!1;zb="beginning";Va=[];y=ba=!1;yb="skimlinksApplyHandlers";Ia=cb=Ha=Ga=J=null;z="";L=r=0;ra=Db=Fa=Cb=Eb=!1;g=this;u=g.location;O="";K=!1;Ea=null;za={};bb=[];qa=da=Ab=0;Hb=["noskim","norewrite"];Ib="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");
Oc=function(){return!0};Ma=function(a){var b;b=document.createElement("a");b.href=a;return ca(b.hostname)};Ob=function(){var a,b,c,d,e,f,i,h,s,Q,l,n,v,t,k,m,o,q,w,x,z,A,B,D,E,F,G,H,I,K,M;Ka=null!=(a=document.getElementsByTagName("html"))?a[0]:void 0;ha=null!=(b=g.skimlinks_included_classes)?b:[];fa=null!=(n=g.skimlinks_excluded_classes)?n:[];ia=null!=(A=g.skimlinks_included_ids)?A:[];V=g.force_location?Ma(g.force_location):u.hostname;C=null!=(F=g.skimlinks_tracking)?F:!1;P=g.skimlinks_site||g.skimlinks_sitename||
!1;Ba=null!=(G=g.skimlinks_domain)?G:"go.redirectingat.com";Ca=null!=(H=g.skimlinks_google)?H:!1;Wa=null!=Ca?Ca:"skimout";N=null!=(I=g.skimlinks_target)?I:!1;pa=null!=(K=g.sl_test)?K:!1;aa=null!=(M=g.skimlinks_exclude)?M:[];T=null!=(c=g.skimlinks_include)?c:[];Da=null!=(d=g.skimlinks_noright)?d:!1;Ua=null!=(e=g.skimlinks_exrel)?e:!1;Ta=null!=(f=g.skimlinks_byrel)?f:!1;Xa=null!=(i=g.skimlinks_blocked_tag)?i:!1;ba=null!=(h=g.skimlinks_revenue_forecast)?h:!1;S=0;y=kc();g.skimlinks_revenue_forecast=!1;
J=null!=(s=g.skimlinks_pub_id)?s:"";if(g.skimlink_legacy_support)g.skimlinks=function(){return!0},g.mugicPopWin&&(g._mugicPopWin=g.mugicPopWin),g.mugicPopWin=function(){return!0},g.mugicRight=function(){return!0},g.mugicRightClick=function(){return!0};r=null!=(Q=g.skimlinks_dnt)?Q:0;L=null!=(l=window.skimlinks_nocookie)?l:!1;L=null!=(v=window.skimlinks_nocookie)?v:!1;Ga=null!=(t=g.noimpressions)?t:!1;(cb=null!=(k=g.noskimlinks||g.noskim)?k:!1)&&(R.skimlinks=!1);(Ha=null!=(m=g.noskimwords||g.noskim)?
m:!1)&&(R.skimwords=!1);(Ia=null!=(o=g.nounlinked||g.noskim)?o:!1)&&(R.unlinked=!1);Eb=null!=(q=g.skim_toolbar)?q:!1;Cb=null!=(w=g.skimlinks_ajax_rerun)?w:!1;Db=null!=(x=g.skimlinks_ipc)?x:!1;ra=null!=(z=g.skimlinks_ipc_diy)?z:!1;g._merchantSettings&&"undefined"===typeof replace_url_field?(Fa=!0,yb="skimlinksApplyHandlersAlt"):Fa=!1;oa=null!=(B=g.skimlinks_ipc_decoration)?B:!1;zb=null!=(D=g.skimlinks_ipc_position)?D:"beginning";Va=null!=(E=g.skimlinks_ipc_domain_whitelist)?E:[];if(g.document&&g.document.referrer)O=
g.document.referrer;tc(V)&&(Ha=cb=!0);C&&!/^[a-z0-9_\\|]+$/i.test(C)&&(C=!1);if("undefined"!==typeof p&&null!==p)p.pag=j.pag=g.force_location||u.href,p.pub=j.pub=J,p.uc=j.uc=C;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();fa.push("noskimlinks");Ea=document.createTextNode("").nodeName;return!0};kc=function(){var a;return"function"===typeof(a=new Date).getTimezoneOffset?a.getTimezoneOffset():void 0};tc=function(a){var b,c,d,e;if(g.noskim_domains){e=
g.noskim_domains;for(c=0,d=e.length;c<d;c++)if(b=e[c],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0}return!1};ca=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();q=function(){return function(){return document.addEventListener?function(a,b,c){if(a&&(a.nodeName||a===g))return a.addEventListener(b,c,!1)}:function(a,b,c){if(a&&(a.nodeName||a===g))return a.attachEvent("on"+b,function(){return 7>m.version&&!window.event?(setTimeout(function(){return c.call(a,
window.event)},100),!0):c.call(a,window.event)})}}}(this)();(function(){return function(){return document.createElement("div").getElementsByClassName?function(a,b){return x(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=gb(b);return hb(a,c)}}})(this)();k=function(){return function(){var a,b;b=[function(){var b,d,e,f;e=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];f=[];for(b=0,d=e.length;b<d;b++)a=e[b],f.push([RegExp(a[0],"g"),a[1]]);return f}()];
return function(c){var d,e,c=encodeURIComponent(c);for(d=0,e=b.length;d<e;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();pb=function(){return function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!V||-1===c.indexOf(V))&&(!V||-1===V.indexOf("."+c))}}}(this)();n=function(a,b,c){var d;3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(e){return null}};D=function(a,b,c){arguments[1]=
"data-"+b;return n.apply(this,arguments)};Rc=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};A=function(){return function(){var a,b;if(String.prototype.trim)return function(a){return null===a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();
Jb=function(a,b){return!x(a,b)?(a.className+=" "+b,!0):!1};wc=function(a){var b,c,d,e,f;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(f in a)w.call(a,f)&&(b=a[f],0<d&&(e+=","),c?e+=o(b):(b=o(b),e+='"'+f+'":'+b),d++);return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};o=function(){return function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?
(a=JSON.stringify,function(b){return a(b)}):wc}}(this)();ta=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();gb=function(a){a=ta(a);return RegExp("\\b"+a+"\\b","i")};x=function(a,b){return a.className?gb(b).test(a.className):!1};hb=function(a,b){var c,d,e,f,i;d=[];a.className&&b.test(a.className)&&d.push(a);i=a.childNodes;for(e=0,f=i.length;e<f;e++)c=i[e],d=d.concat(hb(c,b));return d};Ub=function(a){return-1!==
encodeURIComponent(a).indexOf("%C3%82%C2%A3")};bc=function(a){a=a.innerHTML.slice(0,4);if("http"===a||"www."===a)a.innerHTML="<span style='display:none!important;'>&nbsp;</span>";return!0};sb=function(a){for(var b,c,d,e;a&&a!==Ka;){c=a.id;for(d=0,e=ha.length;d<e;d++)if(b=ha[d],x(a,b))return!1;for(d=0,e=ia.length;d<e;d++)if(b=ia[d],c===b)return!1;for(c=0,d=fa.length;c<d;c++)if(b=fa[c],x(a,b))return!0;a=a.parentNode}return ha.length||ia.length?!0:!1};ma=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+
ta(b)+")|(?:noskim))\\b","i");null!=a&&a!==Ka;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};Vb=function(a,b){var c,d,e,f,i,h;i=O?"&pref="+k(O):"";d=n(a,"data-skimlinks-editor")&&1===parseInt(n(a,"data-skimlinks-editor"))?1:0;x(a,"skimwords-link")?(h=n(a,"data-skimwords-word"),c=n(a,"data-skim-creative"),e=n(a,"data-skim-product"),f=g.skimlinks_domain||"go.redirectingat.com","undefined"!==typeof settings&&null!==settings&&(f=settings.sw_domain||f),b="http://"+f+"/?id="+
J+""+(C?"&xcust="+C:"")+"&xs=2&url="+k(b)+"&xguid="+z+"&isjs=1&xword="+(h?h:"")+"&xcreo="+(c?c:"")+"&xpid="+(e?e:"")+"&xed="+d+"&sref="+k(u)+""+i+""+(r?"&dnt="+r:"")+""+(L?"&fdnt=1":"")+""+(!1!==y?"&xtz="+y:"")):x(a,"skimlinks-inline")?(c=n(a,"data-skim-creative"),b="http://"+Ba+"/?id="+J+""+(P?"&site="+P:"")+""+(pa?"&test="+pa:"")+""+(C?"&xcust="+C:"")+"&xs=8&isjs=1&url="+k(b)+"&xguid="+z+"&xcreo="+(a&&null!=c?c:0)+"&xed="+d+"&sref="+k(u)+"&pref="+k(O)+""+(r?"&dnt="+r:"")+""+(L?"&fdnt=1":"")+""+
(!1!==y?"&xtz="+y:"")):ma(a,"noskimlinks")||(c=n(a,"data-skim-creative"),b="http://"+Ba+"/?id="+J+""+(P?"&site="+P:"")+""+(pa?"&test="+pa:"")+""+(C?"&xcust="+C:"")+"&xs=1&isjs=1&url="+k(b)+"&xguid="+z+"&xcreo="+(a&&null!=c?c:0)+"&xed="+d+"&sref="+k(u)+""+i+""+(r?"&dnt="+r:"")+""+(L?"&fdnt=1":"")+""+(!1!==y?"&xtz="+y:""));K&&(b+="&abp=1");return b};Na=function(a){var b;if((b=a.target||a.srcElement)&&!b.href&&a.currentTarget)b=a.currentTarget;for(;b&&"A"!==b.nodeName;)b=b.parentNode;return b};B=function(a){var b;
b=Na(a);wb(b);if(g.vglnk&&x(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=g.event,a.cancelBubble=!0);return!0};wb=function(a){var b,c,d,e,f;d=!1;e="msie"===m.browser&&7>m.version?1E4:300;b=Ca;if(a&&a.nodeName&&"IMG"===a.nodeName)a=a.parentNode;if(a){f=a.href;c="http://"+Ba;if(f.length>=c.length&&f.substr(0,c.length)===c)return!0;if("msie"===m.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==f.indexOf(c)?f:Vb(a,f);b&&Sc(f);D(a,"skimlinks-orig-link")||
D(a,"skimlinks-orig-link",f);a.href=c;if(d)a.innerHTML=d;setTimeout(function(){return function(){a.href=D(a,"skimlinks-orig-link");D(a,"skimlinks-orig-link","");return!0}}(this),e)}return!0};mb=function(a,b){var c,d;null==b&&(b=La);if(b)for(c in b)if(w.call(b,c)&&(d=b[c],d===a))return!0;return!1};rb=function(a,b){return ba?(mb(a,b)&&(S+=1),!1):mb(a,b)};vc=function(a){var b,c;if(!Xa)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+Xa+"]").toLowerCase();c=Rc(b);if(!c)return!1;c=c.toLowerCase();
c=A(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};xa=function(a){return!a||Ta&&a===Ta||!oc(a)};oc=function(a){var b,c,d,e;U=null;if(!a)return!1;a=a.toLowerCase();if(U)return U[a];U={};b=Ua?[Ua]:[];b=b.concat(Hb);for(c=0,d=b.length;c<d;c++)e=b[c],U[e.toLowerCase()]=!0;return U[a]};fb=function(){var a,b,c,d;F={};W={};P&&aa.push(P);d=aa.concat(Ib);for(b=0,c=d.length;b<c;b++)a=d[b],F[a]=a.length;for(b=0,c=T.length;b<c;b++)a=T[b],W[a]=a.length;return F};nb=function(a){var b,c,d;(null===F||
null===W)&&fb();if(!a)return!1;for(b in F)if(w.call(F,b))if(c=F[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-c)return!0}else if(a===b)return!0;return!1};sc=function(a){var b,c,d;(null===F||null===W)&&fb();if(!a)return!1;if(0===T.length)return!0;for(b in W)if(w.call(W,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===
a.indexOf(b))return!0}else if(a===b)return!0;return!1};Pa=function(a,b){return pb(a,b)&&!nb(b)&&sc(b)};Ra=function(a){if(10>a)return ka=Jc(),setTimeout(function(){return Ra(a+1)},2E3*a)};Jc=function(){var a,b,c,d,e,f,i;b={};d=[];c=[];for(e=0,f=ka.length;e<f;e++)a=ka[e],a.parentNode?c.push(a):b[a.href]=1;i=Z();for(e=0,f=i.length;e<f;e++)a=i[e],b[a.href]&&d.push(a);eb(d);return d.concat(c)};Kb=function(a,b){var c,d,e;d=[];ba&&(a.xrf=1);for(c in a)w.call(a,c)&&(e=a[c],"data"!==c&&d.push(""+c+"="+e));
a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};Tc=function(a){a={call:"track",data:k('{"pubcode":"'+J+'", "referrer":"'+u+'", "pref":"'+O+'", "site":"'+P+'", "url":"'+a+'", "custom":"'+C+'", "xtz":'+y+', "product":"1"}')};r&&(a.dnt=r);L&&(a.fdnt=1);a=Kb(a,"//r.skimresources.com/api/");a=a+"&rnd="+Math.random();hc(a);return!0};vb=function(a){a=Na(a).href;Tc(a);return!0};hc=function(a){var b,c;b=document.getElementsByTagName("body")[0];c=document.createElement("img");c.src=a;c.width=1;c.height=
1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};$=function(a,b,c){var l;var d,e,f,i,h;null==c&&(c={});d=c.charset||null;h=c.target||null;l=null!=(e=c.async)?e:!0,c=l;e=null!=h&&h.document?h.document:document;f=e.getElementsByTagName("head")[0];i=e.createElement("script");i.type="text/javascript";if(d)i.charset=d;if(b)i.onload=i.onreadystatechange=function(a){return function(){var c;c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===d||"loaded"===
d))return i.onload=i.onreadystatechange=null,c=!0,b.call(h),!0}}}(this)();i.async=!1!==c;i.src=a;f.appendChild(i);return i};Z=function(a,b){var c,d,e,f,i,h;d=null;a&&(d=RegExp("\\b"+ta(a)+"\\b","i"));h=[];b||(b=document);e=b.getElementsByTagName("a");for(f=0,i=e.length;f<i;f++){c=e[f];try{c.href&&(!d||c.className&&d.test(c.className))&&h.push(c)}catch(g){}}return h};qb=function(a){return-1!==a.indexOf("itunes.apple.com")||-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?!0:!1};eb=
function(a){var b,c,d,e,f,i,h,g,Q;c=ha.length||ia.length||fa.length;e=[];for(g=0,Q=a.length;g<Q;g++)if(b=a[g],d=ca(b.hostname),b.sl_hidden_domain&&(d=ca(b.sl_hidden_domain)),h=A(b.href),i=n(b,"rel"),f=n(b,"onclick"),n(b,"sl-processed",1),b["sl-processed"]=1,!Fa||!qb(h))if((!c||!sb(b))&&!vc(b))if(rb(d)||qb(h)){if(xa(i)){N&&n(b,"target",N);if("msie"===m.browser){if(Ub(h))continue;bc(b)}null!=f&&-1!==f.toString().indexOf("return false")?q(b,"click",Gc):q(b,"click",B);Ya(b,!1);Oa(b);e.push(b);Da||q(b,
"contextmenu",B);Oc(b)}}else pb(h,d)&&!nb(d)&&xa(i)&&(N&&n(b,"target",N),q(b,"click",vb),Da||q(b,"contextmenu",vb));return e};Gc=function(a){var b;b=Na(a);if(g._mugicPopWin)return g._mugicPopWin(b);B(a);return(N?window.open(b.href):window.open(b.href,N)).focus()};Oa=function(a,b){var c,d,e,f,i,h,s,Q,l;if(g.link_icon||0<a.getAttribute("data-skim-product")&&g.skimwords_product_icon){if(0<a.getElementsByTagName("img").length)return!0;if("msie"===m.browser&&8>m.version)a.style.display="inline-block";
f=d="";null!=b&&(d=g.skimwords_icon_class||"",f=g.skimwords_icon_link_class||"");i=n(a,"title").replace("'","&#39;");e=g.link_icon||g.skimwords_product_icon;x(a,"skimlinks-unlinked")||x(a,"skimwords-link")?(h='data-skim-creative="'+D(a,"skim-creative")+'"',s='data-group-id="'+D(a,"group-id")+'"',l='data-skimwords-word="'+D(a,"skimwords-word")+'"',Q='data-skimwords-id="'+D(a,"skimwords-id")+'"',c=x(a,"skimlinks-unlinked")?"skimlinks-unlinked":"skimwords-link"):c=Q=l=s=h="";c="<a href='"+n(a,"href")+
"' title='"+i+"' "+h+" "+s+" "+l+" "+Q+" style='border:0px;padding:0;margin:0' class='skimlinks-icon-link "+f+" "+c+"' skimlinked='skimlinked' target='_blank'><img src='"+e+"' class='"+d+"' skimlinked='skimlinked' style='margin: 0px 0px -3px 2px !important; float:none !important; border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;' /></a>";d=document.createElement("div");d.innerHTML=c;c=d.childNodes[0];q(c,"mousedown",B);a.appendChild(c)}return!0};
jc=function(a,b){return null!=a.currentStyle?a.currentStyle[b]:window.getComputedStyle?document.defaultView.getComputedStyle(a,null).getPropertyValue(b):!1};la=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],c===a)return!0;return!1};xb=function(a){var b,a=null!=a?a:{};null!=g.skimlinks_runner&&(g.skimlinks_runner.skimlinks=1);b=Z();a.guid&&""===z&&(z=a.guid);"undefined"!==typeof $a&&null!==$a&&null!=E&&null!=E.domains&&$a(E.domains);La=a.merchant_domains||[];ka=eb(b);S+=ka.length;Ia||
tb(a);Nc();return!0};Nc=function(){"undefined"!==typeof Aa&&null!==Aa&&(Db||ra)&&La.length&&Aa();"undefined"!==typeof I&&null!==I&&I("skimlinks");return!0};$b=function(){var a,b,c,d,e,f,i;d=Z();c=[];for(f=0,i=d.length;f<i;f++)a=d[f],b=ca(a.hostname),e=A(a.href),a=n(a,"rel"),b&&Pa(e,b)&&xa(a)&&(G.hasOwnProperty(e)||(G[e]=0),G[e]++,ua[b]||(c.push(b),ua[b]=!0));return{domains:c}};Pb=function(){var a;a=document.getElementsByTagName("body");if(0<a.length)return q(a[0],"click",M),q(a[0],"contextmenu",M)};
M=function(a){var b,c,d;if(g.event)a=g.event;c=a.originalTarget||a.srcElement;b=n(c,"sl-processed")||0;null==c["sl-processed"]&&(b=0);if((d=n(c,"class"))&&(-1!==d.indexOf("skimwords-link")||-1!==d.indexOf("skimlinks-inline")||-1!==d.indexOf("skimlinks-unlinked")))b=!0;if(("IMG"===(null!=c?c.nodeName.toUpperCase():void 0)||"BUTTON"===(null!=c?c.nodeName.toUpperCase():void 0))&&c.parentNode)c=c.parentNode;if("A"===(null!=c?c.nodeName.toUpperCase():void 0)&&0===b)if(b=c,c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&
0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&(c=!1),c&&Pa(b.href,ca(b.hostname))){wb(b);if(g.vglnk&&x(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=g.event,a.cancelBubble=!0);return!0}};Dc=function(a){var b,c,d,e,f,i;b=k('{"pubcode":"'+J+'","domains":_DOMAIN_LIST_,"page":"'+u.href+'"}');e="//r.skimresources.com/api/?callback="+yb+(r?"&dnt="+r:"")+(L?"&fdnt=1":"")+(Eb?"&call=toolbar":"")+"&data="+b;b="msie"===m.browser?2E3:8E3;d=[];for(f=0,i=a.length;f<i;f++)c=a[f],d.push(c),
e.replace("_DOMAIN_LIST_",k(o(d))).length>b&&(d=d.slice(0,-1));e=e.replace("_DOMAIN_LIST_",k(o(d)));return $(e)};ea=function(a){var b,c;b=[];ba&&(a.xrf=1);for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+k(a[c]));return b.join("&")};ya=function(a,b,c){var d,e,f;if("msie"!==m.browser)e=!1,f=new XMLHttpRequest,f.open("POST",a,!0),f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=Gb.call(f,"withCredentials")&&(f.withCredentials=!0),f.async="true",f.onreadystatechange=function(){var a;
if(e)return!0;if(4===f.readyState){e=!0;if(200===f.status){a={};try{a=JSON.parse(f.responseText)}catch(b){try{a=eval("("+f.responseText+")")}catch(d){a={}}}c(a);return!0}return!1}},f.send(b);else if(g.XDomainRequest){if(d=new XDomainRequest,0<=Gb.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){a={}}else try{a=eval("("+d.responseText+")")}catch(e){a=
{}}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=function(){return!1};d.async=!0;try{d.send(b)}catch(i){return!1}}}else return!1;return!0};ub=function(a){var b;b={data:o({pubcode:J,domains:a,page:u.href})};ea(b);Dc(a);return!0};Ic=function(){var a,b,c,d,e,f;c=Z();f=[];for(d=0,e=c.length;d<e;d++)(a=c[d])&&a.href?(b=Ma(a.href),0>Gb.call(cc,b)?(n(a,"sl-processed",0),f.push(a["sl-processed"]=0)):f.push(void 0)):f.push(void 0);return f};Fb=function(){if(window.skimlinksInitialized&&
"function"!==typeof post_skimwords_hook)return!0;window.skimlinksInitialized=!0;Ob();Fa&&Ic();Cb&&Pb();cb||(E=$b(),Ia&&ub(E.domains));"undefined"!==typeof Sa&&null!==Sa&&!Ia&&Sa();"undefined"!==typeof skimwords&&null!==skimwords&&!Ha&&skimwords();"undefined"!==typeof I&&null!==I&&I("skimlinks");return!0};H=function(){if(va)return!1;va=!0;Uc.detect(function(a){K=a;return Fb()});return!0};Fc=function(a){var b,c;b=0;for(c in a)w.call(a,c)&&(b+=1);return b};Ya=function(a,b){var c,d;d=a.style.cssText;
""!==d&&(d+=" ");if(g.link_background)c=g.link_background,-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ";if(null!=g.link_tooltip)a.title=g.link_tooltip;if(b){if(g.skimwords_color)c=g.skimwords_color,-1===c.indexOf("#")&&(c="#"+c),d+="color: "+c+" !important; ";g.skimwords_weight&&(d+="font-weight: "+g.skimwords_weight+" !important; ");if(g.skimwords_decoration)c=g.skimwords_decoration,d="double"===c?d+"border-bottom: 1px double !important; ":"dashed"===c?d+"border-bottom: 1px dashed !important; ":
d+("text-decoration: "+c+" !important; ");if(g.skimwords_style)c=g.skimwords_style,d+="font-style: "+c+" !important; ";if(g.skimwords_link_style)c=g.skimwords_link_style,d+=c+"; ";c=" "+a.className;if(g.skimwords_link_class)c+=" "+g.skimwords_link_class,a.className=c.substring(1);if(g.skimwords_title)a.title=g.skimwords_title;if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%10,1===
c||2===c))a.title=""}a.style.cssText=d;return!0};Mc=function(){return function(){return function(){var a,b,c;if(window.skimlinks_revenue_forecast&&window.skimlinks)return!1;b=function(){if(va)return!0;try{document.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return H()};a=function(){return function(){return document.addEventListener?function(){document.removeEventListener("DOMContentLoaded",a,!1);H();return!0}:document.attachEvent?function(){document.detachEvent("onreadystatechange",
a);H();return!0}:function(){H();return!0}}}(this)();if("complete"===document.readyState)setTimeout(H,1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1),g.addEventListener("load",H,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",a);g.attachEvent("onload",H);c=!1;try{c=null===g.frameElement}catch(d){}document.documentElement.doScroll&&c&&b()}return!0}}}(this)();Xb=function(a,b){return setTimeout(b,a)};g.skimlinksApplyHandlers=xb;g.skimlinksApplyHandlersAlt=
xb;g.skimlinksAjaxHandlerByClass=function(a){var b,c,d;if("function"===typeof document.getElementsByClassName){b=document.getElementsByClassName(a);for(c=0,d=b.length;c<d;c++)a=b[c],q(a,"click",M),q(a,"contextmenu",M);return!0}return!1};g.skimlinksAjaxHandlerById=function(a){return(a=document.getElementById(a))?(q(a,"click",M),q(a,"contextmenu",M),!0):!1};wa=!1;ib=function(a){var b;return a&&-1!==a.indexOf("class=")?(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:a};lc=function(a){za[a]=
za[a]||0;za[a]++;return a+"_"+za[a]};Ja=function(a){var b,c,d;b=c=null;-1!==a.indexOf(".")?(a=a.split("."),d=a[0],b=a[1]):-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],c=a[1].split("]"),c=c[0]):d=a;return{tag:d,id:c,"class":b}};Qa=function(a,b){var c,d,e,f,i,g;e=b.split(",");for(i=0,g=e.length;i<g;i++){b=e[i];b=A(b);b=Ja(b);f=!0;c=
a.className||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";d=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";if(b.tag&&(!a.nodeName||a.nodeName.toLowerCase()!==b.tag))f=!1;if(b["class"]&&(!c||c!==b["class"]&&0!==c.indexOf(b["class"])))f=!1;if(b.id&&(!d||d!==b.id&&-1===d.indexOf(b.id)))f=!1;if(f)return!0}return!1};gc=function(a){var b,c,d,e,f,i;if("undefined"!==typeof document.querySelectorAll)return document.querySelectorAll(a);e=[];a=Ja(a);if(a.tag&&
a["class"]){d=document.getElementsByTagName(a.tag);for(f=0,i=d.length;f<i;f++)b=d[f],(c=b.className||b.getAttribute("class"))&&0===c.indexOf(a["class"])&&e.push(b)}else a.tag&&a.id?(b=document.getElementById(a.id))&&b.nodeName.toLowerCase()===a.tag&&e.push(b):(a=a.tag,e=document.getElementsByTagName(a));return e};nc=function(a,b,c){var d,e,f,i,g;d=[];if("undefined"!==typeof a.querySelectorAll)d=a.querySelectorAll(b);else if(b=Ja(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;f=a.getElementsByTagName(b.tag);
for(i=0,g=f.length;i<g;i++)if(a=f[i],(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)d.push(a);else return!0}else if(b.tag&&b.id){if((a=document.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)d.push(a);else return!0}else b=b.tag,d=a.getElementsByTagName(b);return c?d:0<d.length};ob=function(a,b){return 0===b.length?!1:Qa(a,b.join(","))?!0:a.parentNode?ob(a.parentNode,b):!1};qc=function(a){var b;b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===
a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};ec=function(){var a;a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");
-1!==u.href.indexOf(".google.")?(a.push("td.gac_c"),a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==u.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==u.href.indexOf(".aol.")?(a.push("div.sllLink"),a.push("div.n")):-1!==u.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),
a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};Cc=function(a){var b,c,d,e;c={};for(d=0,e=a.length;d<e;d++)b=a[d],c[b]=!0;return c};na=function(){var a;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f,i,g,s,n,l,j;if(wa)return a;wa=!0;f=this.get_exclude_selector(c);e=this.get_exclude_selector([]);c=f.selector;f=f.needed;e=e.selector;0===b.length&&b.push("body");
b=b.concat(d);for(s=0,l=b.length;s<l;s++){i=b[s];i=ib(i);i=gc(i);for(g=n=0,j=i.length;n<j;g=++n)g=i[g],this.traverse_node(g,f,e,c,d)}return a},traverse_node:function(b,c,d,e,f){var g,h;h=[];g=0;for(h.push({node:b,tagName:"",readOnly:!1,parent_id:null});g<h.length;){if((b=h[g].node)&&!qc(b)&&!ma(b,"noskimwords",!0)&&(!c||!(""!==d&&Qa(b,d)))){h[g].readOnly=!1;if(b.nodeName&&b.nodeName!==Ea){h[g].tagName=b.nodeName;if(null!==h[g].parent_id)h[g].readOnly=h[h[g].parent_id].readOnly;if(!h[g].readOnly)if(c&&
Qa(b,e))h[g].readOnly=!0;else if(la(b.nodeName.toLowerCase(),f))h[g].readOnly=!0;if(la(b.nodeName.toLowerCase(),f))h[g].readOnly=!0}else if(null!==h[g].parent_id)h[g].tagName=h[h[g].parent_id].tagName,h[g].readOnly=h[h[g].parent_id].readOnly;"msie"===m.browser&&9>m.version&&h[g].readOnly||(b.hasChildNodes()?h=this.add_child_nodes(h[g],g,h):this._add(b,!1,h[g].tagName,h[g].readOnly))}g++}return a},is_traversed:function(){return wa},is_good_tag:function(a){return Cc("p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section".split(","))[a.nodeName.toLowerCase()]?
!0:!1},is_html:function(a){return(a=A(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b,c,d;d=a;c={};Ab=0;for(b in d)w.call(d,b)&&(c[b]=d[b],Ab++);return c},get_as_hash_node_dict:function(){var b,c,d;c={};for(b in a)d=a[b],a.hasOwnProperty(b)&&(c[b]=d);return c},get_as_pair_array:function(){var b,c;c=[];for(b in a)w.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var d,e,f,g,h,s;g=[];if(!c){c=document.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};
c=c[0]}a=a.concat(ec());for(d=e=0,f=a.length;e<f;d=++e)a[d]=ib(a[d]);e=!1;f="";for(h=0,s=a.length;h<s;h++)d=a[h],nc(c,d,!1)&&g.push(d);g.length&&(e=!0,f=g.join(",").replace("class=","class^="));return{needed:e,selector:f}},length:function(){return Fc(a)},reset:function(){a=[];return wa=!1},add_child_nodes:function(a,c,d){var e,f,g,h;h=a.node.childNodes;for(f=0,g=h.length;f<g;f++)(e=h[f])&&e.nodeName&&(this._add(e,!1,a.tagName,a.readOnly)||this.is_good_tag(e)&&d.push({node:e,tagName:a.tagName,readOnly:a.readOnly,
parent_id:c}));return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f;f=null;b.nodeName===Ea&&(f=A(b.nodeValue));c=c||!1;if("msie"===m.browser&&9>m.version&&e)return!1;if("msie"!==m.browser||9<=m.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){var c;if(!a)return"";c=A(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,
"");c=""+c+":"+a.substring(0,20);return c=lc(c)}}}();Qc=function(a,b,c,d){var e,f,g,h,s,j,l,k,v,t,m;e=document.createDocumentFragment();l=0;k=[];m=b.nodeValue;h=[];s=b.parentNode;d||(d="skimwords-potential");c||(c="-1");if(s){for(v=0,t=a.length;v<t;v++)g=a[v],j=document.createElement("span"),j.className=d,f=document.createTextNode(m.substring(l,g.start)),e.appendChild(f),j.innerHTML=g.text,e.appendChild(j),l={},l.node=j,l.match=g,n(l,"occurrence",g.target_occurrence),k.push(l),l=g.start+g.text.length,
h.push(f),na.add_node(f,c);a=document.createTextNode(m.substring(l));h.push(a);e.appendChild(a);na.add_node(a,c);s.replaceChild(e,b)}return[k,h]};Yb=function(a,b,c){var d,e,f;if(ba)return!1;d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);f=document.createElement("span");b=document.createDocumentFragment();f.innerHTML=d;if("msie"===m.browser&&9>m.version&&(d=a.previousSibling,e=/^\s/,d&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=
" "),(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[0])))d.nodeValue=" "+d.nodeValue;for(;f.firstChild;)f.firstChild.nodeName===Ea?(d=b.appendChild(f.firstChild),na.add_node(d)):(d=b.appendChild(f.firstChild),null!==d&&!c&&(Ya(d,!0),Oa(d,!0)));if(c=a.parentNode)return c.replaceChild(b,a)};xc=function(a,b){10>parseInt(b)&&(b="0"+b);return"3"+a+"0"+b};Nb=function(a,b){1E7<a&&6!==b&&(a-=1E7);return a};Lc=function(a,b,c){var d,e,f;f=b.phrase;d={};d.w=f.text();d.lp=f.url();if(c)d.t=
Bb,e="unlinked";else{if(0===f.limit())return!1;f.dec_limit();da+=1;d.ed=f.is_editor()?1:0;d.t=xc("02",f.action_type(),f.group_id());e="skimwords";d.pid=0===f.group_id()?0:Nb(f.id(),f.action_type())}Mb(d,e);Yb(a,b,c);return!0};Bb="500005";Rb=function(a){q(a,"click",B);Da||q(a,"contextmenu",B);Ya(a,!1);return Oa(a)};pc=function(a){a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a);return a.length&&""!==a[0]?!0:!1};dc=function(a,b,c,d){var e,f;e=ta(a);
f="";N&&(f='target="'+N+'"');e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+encodeURIComponent(a)+('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:RegExp(e,"i"),repl_regex:RegExp(b,"i"),repl_text:a}};Qb=function(){var a,b,c,d,e;b=Z("skimlinks-unlinked");e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(Rb(a));return e};
tb=function(a){var b,c,d,e;b={};if((c=a.merchant_domains)&&c.length){for(d=0,e=c.length;d<e;d++)a=c[d],b[a]=!0;for(d=0,e=bb.length;d<e;d++)c=bb[d],a=c.match.domain,b.hasOwnProperty(a)&&Lc(c.node,c.match,!0)}Xb(10,function(){return Qb("skimlinks-unlinked")});try{return I("unlinked")}catch(f){return!0}};Zb=function(a,b){var c,d,e,f,g,h,s,n,l,j,k;if(!a||ob(a,["span.skimlinks-unlinked"]))return[[],[]];k=a.data;e=[];h=[];for(l=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;d=
l.exec(k);)if(c=d[0],"link.phrase"!==c)if(g=d.index,0<A(c).length&&-1===c.indexOf("/.")&&-1===c.indexOf("..."))f=c,0!==c.indexOf("http")&&0!==c.indexOf("//")&&(f="msie"===m.browser&&6>=m.version?"http://"+c:"//"+c),d=Ma(f),n=Wb({OriginalPhrase:""+c,Url:f,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(j=dc(""+c,f,Bb,"skimlinks-unlinked"))&&h.push({start:g,text:""+c,domain:d,repl_regex:j.repl_regex,replacement:j.repl_text,regex:j.search_regex,phrase:n,link:f}),e.push(d);else break;if(h.length){s=Qc(h,
a,b,"skimlinks-unlinked");c=s[0];s=s[1];for(l=0,k=c.length;l<k;l++)h=c[l],bb.push(h)}s||(s=[]);return[e,s]};Kc=function(a){var b,c,d;if(aa.length)for(c=0,d=aa.length;c<d;c++)if(b=aa[c],b===a)return!1;if(T.length){for(c=0,d=T.length;c<d;c++)if(b=T[c],b===a)return!0;return!1}return!0};mc=function(){var a,b,c,d,e,f;c=na.get_as_hash_node_dict();for(b in c)if(a=c[b],a.parentNode&&!sb(a)&&!ma(a,"noskimwords")&&!ma(a,"noskimlinks")&&!ma(a,"noskimw")&&(!a.meta||!a.meta.ReadOnly)){a=Zb(a,b);f=a[0];for(d=0,
e=f.length;d<e;d++)a=f[d],!ua[a]&&Kc(a)&&(ua[a]=!0,E.domains.push(a))}return E.domains.length?ub(E.domains):I("unlinked")};Sa=function(){var a;a=document.getElementsByTagName("body");if(a.length&&(a=a[0].textContent||a[0].innerText)&&pc(a))Ha?(na.traverse([],[],[]),mc()):getSkimwordsData("skimwordsSettingsCallback")};g.skimlinksUnlinked=tb;p={pag:"",pub:"",guid:"",uc:"",lnks:{}};ja={};Tb=function(a,b){var c,d,e;e="GBP"===a.currency?"&pound;":"EUR"===a.currency?"&euro;":"$";d=document.createElement("a");
n(d,"href",a.url);n(d,"title",a.title);n(d,"target","_blank");Jb(d,"skimlinks-inline");n(d,"data-skim-creative",b);c=0;ra&&(c=1);n(d,"data-skimlinks-editor",c);c=parseFloat(Math.round(100*a.price)/100).toFixed(2);d.innerHTML=""+a.merchant+" "+e+c;q(d,"mousedown",B);return d};Sb=function(a,b,c,d,e){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+e};fc=function(a,b){var c,d,e,f,g,h,j;c=b.price;if(!c)return"0";d=0;e=1E8;g=0;for(h=0,j=a.length;h<j;h++)f=a[h],f=parseFloat(f.price),
f>d&&(d=f),parseFloat(f)<e&&(e=f),f===c&&g++;return 1<g?"4":c>=d?"3":c<=e?"1":"2"};Pc=function(a,b,c){var d,e,f,g,h;e=!1;for(d=g=0,h=a.length;g<h;d=++g)if(f=a[d],f.url===c){e=d;break}e&&(c=a[e],"beginning"===b?(a[e]=a[0],a[0]=c):"end"===b&&(a[e]=a[a.length-1],a[a.length-1]=c));return a};Hc=function(a){var b,c;if("1"===n(a,"ipc-added")){for(;")"!==(null!=(c=a.nextSibling)?c.textContent.substring(0,1):void 0);)(b=a.nextSibling)&&b.parentNode&&b.parentNode.removeChild(b);if(a&&a.parentNode&&a.nextSibling)return a.parentNode.removeChild(a.nextSibling)}};
Lb=function(a,b,c,d,e,f,i){var h,j,k,l,m,v,t,p,o,q,r,u,w,x;Hc(b);k=!0;m=b;l=!1;c=Pc(c,zb,d);e.hasOwnProperty(d)?(v=e[d],f[v].cnt++):(i[d]={},v={},v.lpid=d,v.cnt=1,v.url=b.href.replace(ga,""),v.prd=[],v.ed=ra?1:0,f.push(v),v=f.length-1,e[d]=v);"cross"===oa?n(b,"style","text-decoration: line-through !important;"):"text"===oa?null!=b.parentNode&&(e=null!=(p=jc(b.parentNode,"color"))?p:"#000",n(b,"style","color: "+e+" !important; text-decoration: none !important;")):"blink"===oa&&n(b,"style","text-decoration: blink !important;");
e=c.length;p=0;if(g.skimlinks_editor)w=b.parentNode,u=document.createElement("span"),r=document.createElement("span"),h=b.cloneNode(!0),u.appendChild(h),u.appendChild(r),u.style.display="inline !important",u.classList.add("sl-select-wrapper"),r.classList.add("sl-select-products"),h.classList.add("sl-select-link");for(h=0,x=c.length;h<x;h++){t=c[h];l=!0;q=t.currency+t.price+t.url+t.title+t.merchant;p+=1;j=fc(c,t);j=Sb(oa,j,e,a,p);if(!i[d].hasOwnProperty(q))o={},o.cur=t.currency,o.mn=t.merchant,o.mid=
t.merchant_id,o.pr=t.price,o.ti=t.title,o.pu=t.url.replace(ga,""),o.cr=j,f[v].prd.push(o),i[d][q]=!0;t=Tb(t,j);k?(q=document.createTextNode(" ("),k=!1):q=document.createTextNode(" | ");g.skimlinks_editor?(r.appendChild(q),r.appendChild(t)):(m.parentNode.insertBefore(q,m.nextSibling),q.parentNode.insertBefore(t,q.nextSibling));m=t}g.skimlinks_editor&&w.replaceChild(u,b);k||(a=document.createTextNode(") "),m.parentNode.insertBefore(a,m.nextSibling));n(b,"ipc-added",1);return l};uc=function(a,b,c){var d,
e;for(e in b)if(w.call(b,e)&&(d=b[e],e===a&&(0===d.length||la(c,d))))return!0;return!1};db=function(a){var b,c,d,e,f,g,h,j,k,l,m;if(!a)return!1;d={};e=[];g={};c=[];j=!1;for(k in a)if(w.call(a,k)&&ja.hasOwnProperty(k)&&(h=a[k],h.length)){f=ja[k];for(l=0,m=f.length;l<m;l++)b=f[l],k=A(b.href),n(b,"rel"),Lb(1,b,h,k,d,e,g)&&(j=!0),c.push({url:k,occurrence:n(b,"data-occurrence"),products:h})}j&&"undefined"!==typeof Za&&null!==Za&&Za(e);"undefined"!==typeof setSelectLinks&&null!==setSelectLinks&&setSelectLinks(c);
return!0};ic=function(){var a;a="//r.skimresources.com/api/select_whitelist.php?callback=selectWhitelistCallback&data="+k(o({pubcode:J,page:u.href}));return $(a)};Ac=function(a){var b,c,d,e,f,g;e="//r.skimresources.com/api/select.php?callback=selectCallback&urls=";b="msie"===m.browser?2E3:8E3;c=[];for(f=0,g=a.length;f<g;f++)d=a[f],c.push(d),d=k(o(c)).length,d+e.length>b&&(c=c.slice(0,-1));if(c.length)return e+=k(o(c)),$(e)};Bc=function(a){var b;b={urls:o(a),debug:1};b=ea(b);(K||!ya("//r.skimresources.com/api/select.php",
b,db))&&Ac(a);return!0};lb=function(a){var b,c,d,e,f,g,h,j,k,l,m,o,p,q,r;if(!1!==a&&0===a.length)return!1;m=[];g={};h=Z();k=0;for(o=0,q=h.length;o<q;o++)if(b=h[o],e=ca(b.hostname),l=A(b.href),j=n(b,"rel"),d=b.childNodes,!Va.length||la(e,Va)){if(d&&d.length){f=!1;for(p=0,r=d.length;p<r;p++)c=d[p],c.nodeName&&"IMG"===c.nodeName.toUpperCase()&&(f=!0);if(f)continue}if(Pa(l,e)&&xa(j)&&rb(e)&&(g.hasOwnProperty(l)||(g[l]=0),g[l]++,n(b,"data-occurrence",g[l]),n(b,"data-select-id",k),k++,!a||uc(l,a,g[l])))if(c=
n(b,"class"),!c||!(-1!==c.indexOf("skimlinks-inline")||-1!==c.indexOf("skimwords-link")))if("undefined"===typeof ja[l]&&(ja[l]=[]),ja[l].push(b),la(l,m)||m.push(l),100<=m.length)break}return 0===m.length?!1:Bc(m)};Aa=function(){return ra?ic():lb(!1)};g.selectCallback=db;g.selectWhitelistCallback=lb;g.skimlinksApplySelect=Aa;Wb=function(a){var b,c,d,e;d=b=null;c=5;a.Limit&&(c=a.Limit);e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return c-1},
limit:function(){return c},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return d?d:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:
[]},title:function(){return a.Unlinked?"":a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return d=a}}};j={pag:"",phr:[],unl:[],pub:"",slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uc:"",t:1};R={skimlinks:!0,skimwords:!0,unlinked:!0};kb=!1;Mb=function(a,b){var c,d,e,f;c=!0;if("skimwords"===b){for(e=0,f=X.length;e<f;e++)if(d=
X[e],c=d.pid?d.pid===a.pid:d.w===a.w)return c;X.push(a)}else if("unlinked"===b){for(e=0,f=Y.length;e<f;e++)d=Y[e],d.w===a.w&&(c=!1);c&&Y.push(a);qa++}return c};zc=function(){var a,b,c,d,e,f;a=8E3;"msie"===m.browser&&(a=2E3);d={};d.guid=z;d.pub=J;d.pag=u.href;d.tz=y;d.dl={};d.typ="l";c="//t.skimresources.net/api/link?data=";f=0;for(e in G)w.call(G,e)&&(b=G[e],f++,d.dl[e]=b,b=c+k(o(d)),b.length>a&&(f--,delete d.dl[e]));f&&(c+=k(o(d)),$(c,!1,{async:!0}));return!0};rc=function(a){for(var b in a)if(w.call(a,
b))return!1;return!0};$a=function(){var a;if(Ga||rc(G))return!1;a={};a.guid=z;a.pub=J;a.pag=u.href;a.dl=G;a.tz=y;a.typ="l";a={data:o(a)};r&&(a.dnt=r);L&&(a.fdnt=1);a=ea(a);if(K||!ya("//t.skimresources.net/api/link",a,ab))return zc()};Sc=function(a){var b,c,d;b=g.pageTracker;d=g.urchinTracker;c="/"+Wa+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;if(g._gaq)b=g._gaq,b.push(["_trackEvent",Wa,"click",a]);return!1};yc=function(a){var b,c,d,e,f;p.tz=y;p.guid=z;p.pref=
O;p.lnks=[];p.typ="s";b=8E3;"msie"===m.browser&&(b=2E3);c="//t.skimresources.net/api/ipc?data=";for(e=0,f=a.length;e<f;e++)d=a[e],p.lnks.push(d),d=c+k(o(p)),d.length>b&&(p.lnks=p.lnks.slice(0,-1));p.lnks.length&&(c+=k(o(p)),$(c,!1,{async:!0}));return!0};Za=function(a){var b;if(Ga)return!1;p.tz=y;p.guid=z;p.pref=O;p.lnks=a;p.typ="s";b={data:o(p)};b=ea(b);(K||!ya("//t.skimresources.net/api/ipc",b,ab))&&yc(a);return!0};ab=function(){return!0};I=function(a){var b,c;if(Ga||kb)return!1;R[a]=!1;a=!0;for(b in R)if(w.call(R,
b)&&(c=R[b],!0===c)){a=!1;break}if(a)return kb=!0,ac()};sa=function(a){var b,c,d,e,f;if(a instanceof Array){c={};for(b=e=0,f=a.length;e<f;b=++e)d=a[b],c[""+b]=d;return c}return a};Ec=function(){var a,b,c,d,e;a=(new Date).getTime()-jb;b=8E3;"msie"===m.browser&&(b=2E3);j.tz=y;j.slc=S;j.swc=null!=da?da:0;j.ulc=null!=qa?qa:0;j.jsl=a;j.guid=z;j.pref=O;j.phr=[];j.unl=[];ba&&(j.xrf=1);a="//t.skimresources.net/api/track.php?";r&&(a=a+"dnt="+r+"&");L&&(a+="fdnt=1&");K&&(a+="abp=1&");a+="data=";for(c=d=0,e=
X.length;d<e;c=++d)c=X[c],j.phr.push(c),c=a+k(o(j).replace(ga,"")),c.length>b&&(j.phr=j.phr.slice(0,-1));for(c=d=0,e=Y.length;d<e;c=++d)c=Y[c],j.unl.push(c),c=a+k(o(j).replace(ga,"")),c.length>b&&(j.unl=j.unl.slice(0,-1));j.phr=sa(j.phr);j.unl=sa(j.unl);b=a+k(o(j).replace(ga,""));$(b,!1,{async:!0});return Ra(1)};ac=function(){var a;a=(new Date).getTime()-jb;j.tz=y;j.slc=S;j.swc=null!=da?da:0;j.ulc=null!=qa?qa:0;j.jsl=a;j.guid=z;j.pref=O;a=j;a.phr=sa(X);a.unl=sa(Y);a={data:o(a)};r&&(a.dnt=r);L&&(a.fdnt=
1);a=ea(a);if(K||!ya("//t.skimresources.net/api/track.php",a,ab))return Ec(),!0;null!=g.skimlinks_runner&&(g.skimlinks_runner.tracking=1);Ra(1);return!0};!g.mugicPopWin&&!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.mugicPopWin=B);!g.mugicRight&&!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.mugicRight=B);g.skimlinksReload=function(){va=!1;H();return!0};!g.skimlink_legacy_support&&!g.skimlinks_revenue_forecast&&(g.skimlinks=Fb);var Uc=new function(a){function b(a,c){e||
1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(f.complete&&g.complete&&(e=!0),e&&"0"!=f.width&&"0"==g.width&&(d=!0))}var d=!1,e=!1,f=null,g=null;this.detect=function(a){b(a,250)};(function(){try{var b=navigator.userAgent.toLowerCase();if(-1==b.indexOf("firefox")&&-1==b.indexOf("chrome")){e=!0;d=!1;return}}catch(j){}b=11*Math.random();f=new Image;f.onload=c;f.src=a.replace(/\*/,1).replace(/\*/,b);g=new Image;g.onload=c;g.src=a.replace(/\*/,2).replace(/\*/,
b)})()}("//p.skimresources.net/px.gif?ch=*&rn=*");Mc()})();
